// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Thu Feb 04 22:06:57 2021

memory memory_inst
(
	.address(address_sig) ,	// input [31:0] address_sig
	.R/Wnot(R/Wnot_sig) ,	// input  R/Wnot_sig
	.clock(clock_sig) ,	// input  clock_sig
	.data_in(data_in_sig) ,	// input [31:0]:ata_in[31:0]] data_in_sig
	.data_out(data_out_sig) 	// output [31:0] data_out_sig
);

